routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();
Route::group(['namespace' => 'User'], function() {
	Route::get('/', 'HomeController@index');
	Route::get('/about', 'HomeController@about');

	Route::get('/about/workshops', 'HomeController@workshops')->name('about.workshops');

	Route::get('/projects/academic', 'projectsController@academic')->name('projects.academic');
	Route::get('/projects/magazine', 'projectsController@magazine')->name('projects.magazine');
	Route::get('/projects/juniors', 'projectsController@juniors')->name('projects.juniors');
	Route::get('/projects/events', 'projectsController@events')->name('projects.events');
	
	Route::get('/events', 'eventsConteroller@events')->name('events');
	Route::get('/events/career5', 'eventsConteroller@career5')->name('events.career5');
	Route::get('/events/opening18', 'eventsConteroller@opening18')->name('events.opening18');
	Route::get('/events/welcome18', 'eventsConteroller@welcome18')->name('events.welcome18');

	Route::get('/events/participants/19/recruitment', 'eventsConteroller@participants19')->name('events.participants19');
	Route::POST('/events/participants/19/recruitment', 'eventsConteroller@participants19Store')->name('events.participants19');
	Route::get('/events/opening/19/recruitment', 'eventsConteroller@opening19')->name('events.opening19');
	Route::POST('/events/opening/19/recruitment', 'eventsConteroller@opening19Store')->name('events.opening19');

	Route::get('/events/memberssecond/19/recruitment', 'eventsConteroller@memberssecond19')->name('events.memberssecond19');
	Route::POST('/events/memberssecond/19/recruitment', 'eventsConteroller@memberssecond19Store')->name('events.memberssecond19');

	// -------------------------------- Career 6 -----------------------------------------------------
	Route::get('/events/career6/recruitment', 'eventsConteroller@career6')->name('events.career6');
	Route::get('/events/career6/recruitment/form/{form}', 'eventsConteroller@career6form')->name('events.career6.form');
	Route::POST('/events/career6/recruitment', 'eventsConteroller@career6Store');
	// -------------------------------- Career 6 -----------------------------------------------------

	// -------------------------------- Highway -----------------------------------------------------
	Route::get('/events/highway/19', 'eventsConteroller@highway19')->name('events.highway19');
	Route::POST('/events/highway/19', 'eventsConteroller@highway19Store')->name('events.highway19');

	// -------------------------------- Highway -----------------------------------------------------
	
	// -------------------------------- High Board -----------------------------------------------------
	Route::get('/events/highboard/20', 'eventsConteroller@highboard20')->name('events.highboard20');
	Route::POST('/events/highboard/20', 'eventsConteroller@highboard20Store')->name('events.highboard20');
	// -------------------------------- High Board -----------------------------------------------------
	
	// -------------------------------- Heads -----------------------------------------------------
	Route::get('/events/heads/20', 'eventsConteroller@heads20')->name('events.heads20');
	// -------------------------------- Heads -----------------------------------------------------

	Route::get('/k19/magazine/m/{month}', 'magazineController@index')->name('k19.magazine.month');
	Route::get('/k19/magazine/h/{headline}', 'magazineController@index_h')->name('k19.magazine.headline');
	Route::get('/k19/magazine/t/{topic}', 'magazineController@topic')->name('k19.magazine.topic');
	
	Route::get('/k19/magazine', 'magazineController@indexApi')->name('k19.magazine');
	Route::get('/k19/magazine/{id}', 'magazineController@getApi')->name('k19.magazine.id');
	
	Route::post('/k19/magazine/c/{topic}', 'magazineController@comment')->name('topic.comment');

	Route::get('/contact', 'ContactController@index')->name('contact');
	Route::post('/contact', 'ContactController@store')->name('contact');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['namespace' => 'Admin'],function(){
	// get admin homepage
	// Route::GET('admin/home', 'adminsController@index');
	// admin profile
	Route::GET('admin/profile', 'ProfileController@index')->name('admin.profile');
	// change profile image
	Route::POST('admin/photo', 'ProfileController@updatePhoto')->name('admin.photo');
	// update admin data
	Route::PUT('admin/update', 'ProfileController@update')->name('admin.update');
	// change admin password
	Route::POST('admin/password', 'ProfileController@password')->name('admin.password');
	// Edit admin education
	Route::GET('admin/education/edit', 'ProfileController@editEducationView')->name('admin.education.edit');
	Route::POST('admin/education/edit', 'ProfileController@editEducation')->name('admin.education.edit');
	// Edit admin experience
	Route::GET('admin/experience/edit', 'ProfileController@editExperienceView')->name('admin.experience.edit');
	Route::POST('admin/experience/edit', 'ProfileController@editExperience')->name('admin.experience.edit');
	// Edit admin personal info
	Route::GET('admin/info/edit', 'ProfileController@editInfoView')->name('admin.info.edit');
	Route::POST('admin/info/edit', 'ProfileController@editInfo')->name('admin.info.edit');
	// get all admins
	Route::resource('admin/admins', 'AdminsController');
	Route::PUT('admin/admins/activate/{admin}', 'AdminsController@activate')->name('admins.activate');

	Route::resource('admin/roles', 'RolesController');
	Route::resource('admin/permissions', 'PermissionsController');
	Route::resource('admin/headlines', 'HeadlinesController');
	Route::resource('admin/topics', 'TopicsController');
	Route::post('admin/topics/{topic}/publish', 'TopicsController@publish')->name('topics.publish');
	Route::resource('admin/events', 'EventsController');
	Route::resource('admin/workshops', 'WorkshopsController');
	
	Route::resource('admin/headsDescription', 'HeadsDescriptionController');
	
	Route::GET('admin/participants19', 'Participants19Controller@index')->name('participants19.index');
	Route::GET('admin/participants19/rejected', 'Participants19Controller@rejected')->name('participants19.rejected');
	Route::POST('admin/participants19/rejected', 'Participants19Controller@rejectedStore')->name('participants19.rejected');
	
	Route::GET('admin/memberssecond19', 'MembersSecondController@index')->name('memberssecond19.index');
	
	Route::GET('admin/opening19', 'Opening19Controller@index')->name('opening19.index');
	Route::GET('admin/opening19/mail', 'Opening19Controller@mail')->name('opening19.mail');
	
	Route::GET('admin/career6', 'Career6Controller@index')->name('career6.index');
	Route::GET('admin/career6/sessions', 'Career6Controller@sessions')->name('career6.session');
	Route::GET('admin/career6/sessions/create', 'Career6Controller@create')->name('career6.session.create');
	Route::POST('admin/career6/sessions/create', 'Career6Controller@store');
	Route::GET('admin/career6/sessions/{session}/edit', 'Career6Controller@edit')->name('career6.session.edit');
	Route::GET('admin/career6/mail', 'Career6Controller@mail')->name('career6.mail');
	Route::PUT('admin/career6/sessions/{session}/update', 'Career6Controller@update')->name('career6.session.update');
	Route::POST('admin/career6/sessions/status/{session}', 'Career6Controller@status')->name('career6.session.status');
	
	// Highway
	Route::GET('admin/highway19', 'Highway19Controller@index')->name('highway19.index');
	Route::GET('admin/highway19/data', 'Highway19Controller@show')->name('highway19.data');
	Route::POST('admin/highway19/data', 'Highway19Controller@data')->name('highway19.data');

	// High Board 20
	Route::GET('admin/highboard20', 'HighBoard20Controller@index')->name('highboard20.index');

	Route::GET('admin/file', 'Career6Controller@file');
	Route::resource('admin/contact', 'ContactController');
});



// Admin routes
Route::group(['namespace' => 'Auth'],function(){
	// get admin login page
	Route::GET('admin','LoginController@showLoginForm')->name('admin.login');
	// login with admin
	Route::POST('admin','LoginController@login');
	// send email for admin to change password
	Route::POST('admin-password/email','ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	// show page of admin to write his email to change password
	Route::GET('admin-password/reset','ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	// reset admin password
	Route::POST('admin-password/reset','ResetPasswordController@reset');
	// get page where admin reset password
	Route::GET('admin-password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');
	//logout
	Route::POST('logout','LoginController@logout');
});

app/Models/HeadsDescription.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class HeadsDescription extends Model
{
    protected $fillable = [
        'name', 'description', 'image'
    ];
}

app/Http/Controllers/Admin/HeadsDescriptionController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\HeadsDescription;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class HeadsDescriptionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->can('headsDescription.view')) {
            $headsDescription = HeadsDescription::all();
            return view('admin.headsDescription.index', compact('headsDescription'));
        }
        abort(404);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->can('headsDescription.create')) {
            return view('admin.headsDescription.create');
        }
        abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Auth::user()->can('headsDescription.create')) {
            $this->validate($request, [
                'name' => 'required|string',
                'photo' => 'required|image',
                'description' => 'required|string',
            ]);
            $filePath = $request->photo->store('/public/heads');
            $request['image'] = $filePath;
            HeadsDescription::create($request->all());
            return back()->with('Added Successfully!!');
        }
        abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/headsDescription/create.blade.php
@extends('admin.layouts.app')

@section('title')
New Heads Description
@endsection

@section('head')
<link rel="stylesheet" href="{{ asset('/admin_style/css/froala/froala_editor.css') }}">
<link rel="stylesheet" href="{{ asset('/admin_style/css/froala/froala_style.css') }}">
<link rel="stylesheet" href="{{ asset('/admin_style/css/froala/plugins/code_view.css') }}">
<link rel="stylesheet" href="{{ asset('/admin_style/css/froala/plugins/image_manager.css') }}">
<link rel="stylesheet" href="{{ asset('/admin_style/css/froala/plugins/image.css') }}">
<link rel="stylesheet" href="{{ asset('/admin_style/css/froala/plugins/table.css') }}">
<link rel="stylesheet" href="{{ asset('/admin_style/css/froala/plugins/video.css') }}">
@endsection


@section('content')

	<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Heads Description
      </h1>
    </section>
	<section class="content">
	      <div class="row">
	        <div class="col-xs-12">
    			<div class="box">
	            <div class="box-header">
	              <h3 class="box-title">Add new head description</h3>
	            </div>
	            <!-- /.box-header -->
	            <div class="box-body">
	              @foreach ($errors->all() as $error)
        					<div class="alert alert-danger col-sm-9 col-sm-offset-3">{{ $error }}</div>
        				@endforeach

				@if (session('error'))
				    <div class="alert alert-danger col-sm-9 col-sm-offset-3">
				        {{ session('error') }}
				    </div>
				@endif

                <form class="form-horizontal" action="{{ route('headsDescription.store') }}" method="POST" enctype="multipart/form-data">
                	{{ csrf_field() }}
                  <div class="form-group">
                    <label for="inputName" class="col-sm-3 control-label">Name</label>

                    <div class="col-sm-9">
                      <input type="text" class="form-control" autofocus id="inputName" placeholder="Name" required name="name" value="{{ old('name') }}">
                    </div>
                  </div>
				  
				  <div class="form-group">
                    <label for="inputName" class="col-sm-3 control-label">Image</label>

                    <div class="col-sm-9">
                      <input type="file" class="form-control" autofocus id="inputImage" placeholder="Image" required name="photo" accept="image/*">
                    </div>
                  </div>

				  <div class="form-group">
                    <label for="inputName" class="col-sm-3 control-label">Description</label>

                    <div class="col-sm-9">
						<textarea name="description" id="bodyTextarea" required>{{ old('description') }}</textarea>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                      <button type="submit" class="btn bg-red">Submit</button>
                    </div>
                  </div>
                </form>
	            </div>
	            <!-- /.box-body -->
	          </div>
	          <!-- /.box -->
	      </div>
	  </div>
	</section>

</div>

@endsection

@section('footer')
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/froala_editor.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/align.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/code_beautifier.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/code_view.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/draggable.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/image.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/image_manager.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/link.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/lists.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/paragraph_format.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/paragraph_style.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/table.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/video.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/url.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/entities.min.js') }}"></script>

<script>
	$(function(){
	  $('#bodyTextarea')
		.froalaEditor({enter: $.FroalaEditor.ENTER_P, placeholderText: "Write the content of the magazine..."})
	});
</script>
@endsection

resources/views/admin/headsDescription/index.blade.php
@extends('admin.layouts.app')

@section('title')
Heads Description
@endsection

@section('head')
	<link rel="stylesheet" href="{{ asset('/admin_style/css/dataTables.bootstrap.css') }}">
@endsection

@section('content')


	<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Heads Description
      </h1>
    </section>
	<section class="content">
	      <div class="row">
	        <div class="col-xs-12">
    			<div class="box">
	            <div class="box-header">
	              <h3 class="box-title">Heads Description Table</h3>
	              @can('headsDescription.create', Auth::user())
	              	<a type="button" href="{{ route('headsDescription.create') }}" class="btn btn-success btn-flat pull-right">Add New head</a>
	              @endcan
	            </div>
	            <!-- /.box-header -->
	            <div class="box-body">
	            	@if (session('status'))
					    <div class="alert alert-success">
					        {{ session('status') }}
					    </div>
					@endif
	              <table id="example1" class="table table-bordered table-striped">
	                <thead>
	                <tr>
	                  <th>#</th>
	                  <th>Name</th>
	                  <th>Description</th>
	                  <th>Controls</th>
	                  <th>Added From</th>
	                  <th>Updated From</th>
	                </tr>
	                </thead>

	                <tbody>

	                @foreach ($headsDescription as $head)
	                	<tr>
	                		<td>{{ $loop->index + 1 }}</td>
	                		<td>{{ $head->name }}</td>
	                		<td>{!! $head->description !!}</td>
	                		<td>
	                			@can('headsDescription.update', Auth::user())
	                				<a href="{{ route('headsDescription.edit', $head->id) }}" class="btn btn-warning btn-xs"><i class="fa fa-edit"></i></a>
	                			@endcan

	                			@can('headsDescription.delete', Auth::user())
		                			<a 
										href="#" 
										class="btn btn-danger btn-xs"
										onclick="
			                  					event.preventDefault();
			                  					if(confirm('Are you sure you want to delete this account?')) {
			                  						$(this).siblings('form').submit();
			                  					}"
									><i class="fa fa-times"></i></a>
									<form action="{{ route('headsDescription.destroy',$head->id) }}" method="POST">
								        {{ csrf_field() }}
								        {{ method_field('DELETE') }}
								    </form>
								@endcan
	                		</td>
	                		<td>{{ $head->created_at->diffForHumans() }}</td>
	                		<td>{{ $head->updated_at->diffForHumans() }}</td>
	                	</tr>
	                @endforeach

	                </tbody>

	                <tfoot>
	                <tr>
	                  <th>#</th>
	                  <th>Name</th>
	                  <th>Description</th>
	                  <th>Controls</th>
	                  <th>Added From</th>
	                  <th>Updated From</th>
	                </tr>
	                </tfoot>
	              </table>
	            </div>
	            <!-- /.box-body -->
	          </div>
	          <!-- /.box -->
	      </div>
	  </div>
	</section>

</div>


@endsection

@section('footer')

<script src="{{ asset('/admin_style/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('/admin_style/js/dataTables.bootstrap.min.js') }}"></script>
<!-- page script -->
<script>
  $(function () {
  	$("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false
    });
  });
</script>

@endsection