routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();
Route::group(['namespace' => 'User'], function() {
	Route::get('/', 'HomeController@index');
	Route::get('/about', 'HomeController@about');

	Route::get('/about/workshops', 'HomeController@workshops')->name('about.workshops');

	Route::get('/projects/academic', 'projectsController@academic')->name('projects.academic');
	Route::get('/projects/magazine', 'projectsController@magazine')->name('projects.magazine');
	Route::get('/projects/juniors', 'projectsController@juniors')->name('projects.juniors');
	Route::get('/projects/events', 'projectsController@events')->name('projects.events');
	
	Route::get('/events', 'eventsConteroller@events')->name('events');
	Route::get('/events/career5', 'eventsConteroller@career5')->name('events.career5');
	Route::get('/events/opening18', 'eventsConteroller@opening18')->name('events.opening18');
	Route::get('/events/welcome18', 'eventsConteroller@welcome18')->name('events.welcome18');

	Route::get('/events/participants/19/recruitment', 'eventsConteroller@participants19')->name('events.participants19');
	Route::POST('/events/participants/19/recruitment', 'eventsConteroller@participants19Store')->name('events.participants19');
	Route::get('/events/opening/19/recruitment', 'eventsConteroller@opening19')->name('events.opening19');
	Route::POST('/events/opening/19/recruitment', 'eventsConteroller@opening19Store')->name('events.opening19');

	Route::get('/events/memberssecond/19/recruitment', 'eventsConteroller@memberssecond19')->name('events.memberssecond19');
	Route::POST('/events/memberssecond/19/recruitment', 'eventsConteroller@memberssecond19Store')->name('events.memberssecond19');

	// -------------------------------- Career 6 -----------------------------------------------------
	Route::get('/events/career6/recruitment', 'eventsConteroller@career6')->name('events.career6');
	Route::get('/events/career6/recruitment/form/{form}', 'eventsConteroller@career6form')->name('events.career6.form');
	Route::POST('/events/career6/recruitment', 'eventsConteroller@career6Store');
	// -------------------------------- Career 6 -----------------------------------------------------

	// -------------------------------- Highway -----------------------------------------------------
	Route::get('/events/highway/19', 'eventsConteroller@highway19')->name('events.highway19');
	Route::POST('/events/highway/19', 'eventsConteroller@highway19Store')->name('events.highway19');

	// -------------------------------- Highway -----------------------------------------------------
	
	// -------------------------------- High Board -----------------------------------------------------
	Route::get('/events/highboard/20', 'eventsConteroller@highboard20')->name('events.highboard20');
	Route::POST('/events/highboard/20', 'eventsConteroller@highboard20Store')->name('events.highboard20');
	// -------------------------------- High Board -----------------------------------------------------
	
	// -------------------------------- Heads -----------------------------------------------------
	Route::get('/events/heads/20', 'eventsConteroller@heads20')->name('events.heads20');
	// -------------------------------- Heads -----------------------------------------------------

	Route::get('/k19/magazine/m/{month}', 'magazineController@index')->name('k19.magazine.month');
	Route::get('/k19/magazine/h/{headline}', 'magazineController@index_h')->name('k19.magazine.headline');
	Route::get('/k19/magazine/t/{topic}', 'magazineController@topic')->name('k19.magazine.topic');
	
	Route::get('/k19/magazine', 'magazineController@indexApi')->name('k19.magazine');
	Route::get('/k19/magazine/{id}', 'magazineController@getApi')->name('k19.magazine.id');
	
	Route::post('/k19/magazine/c/{topic}', 'magazineController@comment')->name('topic.comment');

	Route::get('/contact', 'ContactController@index')->name('contact');
	Route::post('/contact', 'ContactController@store')->name('contact');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['namespace' => 'Admin'],function(){
	// get admin homepage
	// Route::GET('admin/home', 'adminsController@index');
	// admin profile
	Route::GET('admin/profile', 'ProfileController@index')->name('admin.profile');
	// change profile image
	Route::POST('admin/photo', 'ProfileController@updatePhoto')->name('admin.photo');
	// update admin data
	Route::PUT('admin/update', 'ProfileController@update')->name('admin.update');
	// change admin password
	Route::POST('admin/password', 'ProfileController@password')->name('admin.password');
	// Edit admin education
	Route::GET('admin/education/edit', 'ProfileController@editEducationView')->name('admin.education.edit');
	Route::POST('admin/education/edit', 'ProfileController@editEducation')->name('admin.education.edit');
	// Edit admin experience
	Route::GET('admin/experience/edit', 'ProfileController@editExperienceView')->name('admin.experience.edit');
	Route::POST('admin/experience/edit', 'ProfileController@editExperience')->name('admin.experience.edit');
	// Edit admin personal info
	Route::GET('admin/info/edit', 'ProfileController@editInfoView')->name('admin.info.edit');
	Route::POST('admin/info/edit', 'ProfileController@editInfo')->name('admin.info.edit');
	// get all admins
	Route::resource('admin/admins', 'AdminsController');
	Route::PUT('admin/admins/activate/{admin}', 'AdminsController@activate')->name('admins.activate');

	Route::resource('admin/roles', 'RolesController');
	Route::resource('admin/permissions', 'PermissionsController');
	Route::resource('admin/headlines', 'HeadlinesController');
	Route::resource('admin/topics', 'TopicsController');
	Route::post('admin/topics/{topic}/publish', 'TopicsController@publish')->name('topics.publish');
	Route::resource('admin/events', 'EventsController');
	Route::resource('admin/workshops', 'WorkshopsController');
	
	Route::resource('admin/headsDescription', 'HeadsDescriptionController');
	
	Route::GET('admin/participants19', 'Participants19Controller@index')->name('participants19.index');
	Route::GET('admin/participants19/rejected', 'Participants19Controller@rejected')->name('participants19.rejected');
	Route::POST('admin/participants19/rejected', 'Participants19Controller@rejectedStore')->name('participants19.rejected');
	
	Route::GET('admin/memberssecond19', 'MembersSecondController@index')->name('memberssecond19.index');
	
	Route::GET('admin/opening19', 'Opening19Controller@index')->name('opening19.index');
	Route::GET('admin/opening19/mail', 'Opening19Controller@mail')->name('opening19.mail');
	
	Route::GET('admin/career6', 'Career6Controller@index')->name('career6.index');
	Route::GET('admin/career6/sessions', 'Career6Controller@sessions')->name('career6.session');
	Route::GET('admin/career6/sessions/create', 'Career6Controller@create')->name('career6.session.create');
	Route::POST('admin/career6/sessions/create', 'Career6Controller@store');
	Route::GET('admin/career6/sessions/{session}/edit', 'Career6Controller@edit')->name('career6.session.edit');
	Route::GET('admin/career6/mail', 'Career6Controller@mail')->name('career6.mail');
	Route::PUT('admin/career6/sessions/{session}/update', 'Career6Controller@update')->name('career6.session.update');
	Route::POST('admin/career6/sessions/status/{session}', 'Career6Controller@status')->name('career6.session.status');
	
	// Highway
	Route::GET('admin/highway19', 'Highway19Controller@index')->name('highway19.index');
	Route::GET('admin/highway19/data', 'Highway19Controller@show')->name('highway19.data');
	Route::POST('admin/highway19/data', 'Highway19Controller@data')->name('highway19.data');

	// High Board 20
	Route::GET('admin/highboard20', 'HighBoard20Controller@index')->name('highboard20.index');

	Route::GET('admin/file', 'Career6Controller@file');
	Route::resource('admin/contact', 'ContactController');
});



// Admin routes
Route::group(['namespace' => 'Auth'],function(){
	// get admin login page
	Route::GET('admin','LoginController@showLoginForm')->name('admin.login');
	// login with admin
	Route::POST('admin','LoginController@login');
	// send email for admin to change password
	Route::POST('admin-password/email','ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	// show page of admin to write his email to change password
	Route::GET('admin-password/reset','ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	// reset admin password
	Route::POST('admin-password/reset','ResetPasswordController@reset');
	// get page where admin reset password
	Route::GET('admin-password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');
	//logout
	Route::POST('logout','LoginController@logout');
});

resources/views/admin/admins/create.blade.php
@extends('admin.layouts.app')

@section('title')
New Admin
@endsection

@section('head')
  <link rel="stylesheet" href="{{ asset('/admin_style/js/select2/select2.min.css') }}">
@endsection

@section('content')

	<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Admins
      </h1>
    </section>
	<section class="content">
	      <div class="row">
	        <div class="col-xs-12">
    			<div class="box">
	            <div class="box-header">
	              <h3 class="box-title">Add new Admin</h3>
	            </div>
	            <!-- /.box-header -->
	            <div class="box-body">
	              @foreach ($errors->all() as $error)
        					<div class="alert alert-danger col-sm-9 col-sm-offset-3">{{ $error }}</div>
        				@endforeach

            		@if (session('error'))
            		    <div class="alert alert-danger col-sm-9 col-sm-offset-3">
            		        {{ session('error') }}
            		    </div>
            		@endif

                @if (session('status'))
                      <div class="alert alert-success">
                          {{ session('status') }}
                      </div>
                  @endif

                <form class="form-horizontal" action="{{ route('admins.store') }}" method="POST">
                	{{ csrf_field() }}
                  <div class="form-group">
                    <label for="inputName" class="col-sm-3 control-label">Name</label>

                    <div class="col-sm-9">
                      <input type="text" class="form-control" autofocus id="inputName" placeholder="Name" required name="name" value="{{ old('name') }}">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputEmail" class="col-sm-3 control-label">Email</label>

                    <div class="col-sm-9">
                      <input type="email" class="form-control" id="inputEmail" placeholder="Email" required name="email" value="{{ old('email') }}">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputMobile" class="col-sm-3 control-label">Role</label>

                    <div class="col-sm-9">
                      <select name="role" class="form-control select2" required style="width: 100%;">
                        <option value="">Choose role</option>
                        @foreach ($roles as $role)
                          <option value="{{ $role->id }}">{{ $role->position }} {{ $role->committee }}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputSkills" class="col-sm-3 control-label">Password</label>

                    <div class="col-sm-9">
                      <input type="password" class="form-control" id="inputSkills" placeholder="Password" required name="password">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputPassword" class="col-sm-3 control-label">Confirm Password</label>

                    <div class="col-sm-9">
                      <input type="password" class="form-control" id="inputPassword" placeholder="Confirm Password" required  name="password_confirmation">
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                      <button type="submit" class="btn bg-red">Submit</button>
                    </div>
                  </div>
                </form>
	            </div>
	            <!-- /.box-body -->
	          </div>
	          <!-- /.box -->
	      </div>
	  </div>
	</section>

</div>

@endsection

@section('footer')
  <script src="{{ asset('admin_style/js/select2/select2.full.min.js') }}"></script>
  <script>
    $(function () {
      //Initialize Select2 Elements
      $(".select2").select2();
    });
  </script>
@endsection

resources/views/admin/admins/edit.blade.php
@extends('admin.layouts.app')

@section('title')
Edit Admin
@endsection

@section('head')
  <link rel="stylesheet" href="{{ asset('/admin_style/js/select2/select2.min.css') }}">
@endsection

@section('content')

	<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Edit {{ $admin->name }}
      </h1>
    </section>
	<section class="content">
	      <div class="row">
	        <div class="col-xs-12">
    			<div class="box">
	            <div class="box-header">
	              <h3 class="box-title">Edit Admin</h3>
	            </div>
	            <!-- /.box-header -->
	            <div class="box-body">
	              @foreach ($errors->all() as $error)
        					<div class="alert alert-danger col-sm-9 col-sm-offset-3">{{ $error }}</div>
        				@endforeach

				@if (session('error'))
				    <div class="alert alert-danger col-sm-9 col-sm-offset-3">
				        {{ session('error') }}
				    </div>
				@endif

                <form class="form-horizontal" action="{{ route('admins.update', $admin->id) }}" method="POST">
                	{{ csrf_field() }}
                  {{ method_field('PUT') }}
                  <div class="form-group">
                    <label for="inputName" class="col-sm-3 control-label">Name</label>

                    <div class="col-sm-9">
                      <input type="text" class="form-control" id="inputName" placeholder="Name" required name="name" value="{{ $admin->name or old('name') }}">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputEmail" class="col-sm-3 control-label">Email</label>

                    <div class="col-sm-9">
                      <input type="email" class="form-control" id="inputEmail" placeholder="Email" required name="email" value="{{ $admin->email or old('email') }}">
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="inputMobile" class="col-sm-3 control-label">Role</label>

                    <div class="col-sm-9">
                      <select name="role" class="form-control select2" required style="width: 100%;">
                        <option value="">Choose role</option>
                        @foreach ($roles as $role)
                          @if ($admin->role == $role->id)
                            <option selected value="{{ $role->id }}">{{ $role->position }} {{ $role->committee }}</option>
                          @else
                            <option value="{{ $role->id }}">{{ $role->position }} {{ $role->committee }}</option>
                          @endif
                        @endforeach
                      </select>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                      <button type="submit" class="btn bg-red">Submit</button>
                    </div>
                  </div>
                </form>
	            </div>
	            <!-- /.box-body -->
	          </div>
	          <!-- /.box -->
	      </div>
	  </div>
	</section>

</div>

@endsection

@section('footer')
  <script src="{{ asset('admin_style/js/select2/select2.full.min.js') }}"></script>
  <script>
    $(function () {
      //Initialize Select2 Elements
      $(".select2").select2();
    });
  </script>
@endsection

resources/views/admin/admins/index.blade.php
@extends('admin.layouts.app')

@section('title')
Admins
@endsection

@section('head')
	<link rel="stylesheet" href="{{ asset('/admin_style/css/dataTables.bootstrap.css') }}">
@endsection

@section('content')


	<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Admins
      </h1>
    </section>
	<section class="content">
	      <div class="row">
	        <div class="col-xs-12">
    			<div class="box">
	            <div class="box-header">
	              <h3 class="box-title">Admins Table</h3>
	              @can('admins.create', Auth::user())
	              	<a type="button" href="{{ route('admins.create') }}" class="btn btn-success btn-flat pull-right">Add New Admin</a>
	              @endcan
	            </div>
	            <!-- /.box-header -->
	            <div class="box-body">
	            	@if (session('status'))
					    <div class="alert alert-success">
					        {{ session('status') }}
					    </div>
					@endif
	              <table id="example1" class="table table-bordered table-striped">
	                <thead>
	                <tr>
	                  <th>#</th>
	                  <th>Name</th>
	                  <th>Email</th>
	                  <th>Role</th>
	                  <th>Active</th>
	                  <th>Controls</th>
	                  <th>Added From</th>
	                  <th>Updated From</th>
	                </tr>
	                </thead>

	                <tbody>

	                @foreach ($admins as $admin)
	                	<tr>
	                		<td>{{ $loop->index + 1 }}</td>
	                		<td>{{ $admin->name }}</td>
	                		<td>{{ $admin->email }}</td>
	                		<td>{{ $admin->position->committee }} {{ $admin->position->position }}</td>
	                		<td>
								@can('admins.update', Auth::user())
									@if ($admin->active)
										<a 
											href="#" 
											class="btn btn-success btn-xs"
											onclick="
													event.preventDefault();
													if(confirm('Are you sure you want to deactivate this account?')) {
														$(this).siblings('form').submit();
													}"
										 data-toggle="tooltip" data-placement="top" title="Active"><i class="fa fa-check"></i></a>
										<form action="{{ route('admins.activate',$admin->id) }}" method="POST">
											{{ csrf_field() }}
											{{ method_field('PUT') }}
										</form>
									@else
										<a 
											href="#" 
											class="btn btn-danger btn-xs"
											onclick="
													event.preventDefault();
													if(confirm('Are you sure you want to activate this account?')) {
														$(this).siblings('form').submit();
													}"
										data-toggle="tooltip" data-placement="top" title="Not Active"><i class="fa fa-times"></i></a>
										<form action="{{ route('admins.activate',$admin->id) }}" method="POST">
											{{ csrf_field() }}
											{{ method_field('PUT') }}
										</form>
									@endif
								@endcan
							</td>
	                		<td>
	                			@can('admins.update', Auth::user())
	                				<a href="{{ route('admins.edit', $admin->id) }}" class="btn btn-warning btn-xs"><i class="fa fa-edit"></i></a>
	                			@endcan
	                			@can('admins.delete', Auth::user())
		                			<a 
										href="#" 
										class="btn btn-danger btn-xs"
										onclick="
			                  					event.preventDefault();
			                  					if(confirm('Are you sure you want to delete this account?')) {
			                  						$(this).siblings('form').submit();
			                  					}"
									><i class="fa fa-times"></i></a>
									<form action="{{ route('admins.destroy',$admin->id) }}" method="POST">
								        {{ csrf_field() }}
								        {{ method_field('DELETE') }}
								    </form>
								@endcan
	                		</td>
	                		<td>{{ $admin->created_at->diffForHumans() }}</td>
	                		<td>{{ $admin->updated_at->diffForHumans() }}</td>
	                	</tr>
	                @endforeach

	                </tbody>

	                <tfoot>
	                <tr>
	                  <th>#</th>
	                  <th>Name</th>
	                  <th>Email</th>
	                  <th>Role</th>
	                  <th>Controls</th>
	                  <th>Added From</th>
	                  <th>Updated From</th>
	                </tr>
	                </tfoot>
	              </table>
	            </div>
	            <!-- /.box-body -->
	          </div>
	          <!-- /.box -->
	      </div>
	  </div>
	</section>

</div>


@endsection

@section('footer')

<script src="{{ asset('/admin_style/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('/admin_style/js/dataTables.bootstrap.min.js') }}"></script>
<!-- page script -->
<script>
  $(function () {
  	$("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false
    });
  });
</script>

@endsection