routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes();
Route::group(['namespace' => 'User'], function() {
	Route::get('/', 'HomeController@index');
	Route::get('/about', 'HomeController@about');

	Route::get('/about/workshops', 'HomeController@workshops')->name('about.workshops');

	Route::get('/projects/academic', 'projectsController@academic')->name('projects.academic');
	Route::get('/projects/magazine', 'projectsController@magazine')->name('projects.magazine');
	Route::get('/projects/juniors', 'projectsController@juniors')->name('projects.juniors');
	Route::get('/projects/events', 'projectsController@events')->name('projects.events');
	
	Route::get('/events', 'eventsConteroller@events')->name('events');
	Route::get('/events/career5', 'eventsConteroller@career5')->name('events.career5');
	Route::get('/events/opening18', 'eventsConteroller@opening18')->name('events.opening18');
	Route::get('/events/welcome18', 'eventsConteroller@welcome18')->name('events.welcome18');

	Route::get('/events/participants/19/recruitment', 'eventsConteroller@participants19')->name('events.participants19');
	Route::POST('/events/participants/19/recruitment', 'eventsConteroller@participants19Store')->name('events.participants19');
	Route::get('/events/opening/19/recruitment', 'eventsConteroller@opening19')->name('events.opening19');
	Route::POST('/events/opening/19/recruitment', 'eventsConteroller@opening19Store')->name('events.opening19');

	Route::get('/events/memberssecond/19/recruitment', 'eventsConteroller@memberssecond19')->name('events.memberssecond19');
	Route::POST('/events/memberssecond/19/recruitment', 'eventsConteroller@memberssecond19Store')->name('events.memberssecond19');

	// -------------------------------- Career 6 -----------------------------------------------------
	Route::get('/events/career6/recruitment', 'eventsConteroller@career6')->name('events.career6');
	Route::get('/events/career6/recruitment/form/{form}', 'eventsConteroller@career6form')->name('events.career6.form');
	Route::POST('/events/career6/recruitment', 'eventsConteroller@career6Store');
	// -------------------------------- Career 6 -----------------------------------------------------

	// -------------------------------- Highway -----------------------------------------------------
	Route::get('/events/highway/19', 'eventsConteroller@highway19')->name('events.highway19');
	Route::POST('/events/highway/19', 'eventsConteroller@highway19Store')->name('events.highway19');

	// -------------------------------- Highway -----------------------------------------------------
	
	// -------------------------------- High Board -----------------------------------------------------
	Route::get('/events/highboard/20', 'eventsConteroller@highboard20')->name('events.highboard20');
	Route::POST('/events/highboard/20', 'eventsConteroller@highboard20Store')->name('events.highboard20');
	// -------------------------------- High Board -----------------------------------------------------
	
	// -------------------------------- Heads -----------------------------------------------------
	Route::get('/events/heads/20', 'eventsConteroller@heads20')->name('events.heads20');
	// -------------------------------- Heads -----------------------------------------------------

	Route::get('/k19/magazine/m/{month}', 'magazineController@index')->name('k19.magazine.month');
	Route::get('/k19/magazine/h/{headline}', 'magazineController@index_h')->name('k19.magazine.headline');
	Route::get('/k19/magazine/t/{topic}', 'magazineController@topic')->name('k19.magazine.topic');
	
	Route::get('/k19/magazine', 'magazineController@indexApi')->name('k19.magazine');
	Route::get('/k19/magazine/{id}', 'magazineController@getApi')->name('k19.magazine.id');
	
	Route::post('/k19/magazine/c/{topic}', 'magazineController@comment')->name('topic.comment');

	Route::get('/contact', 'ContactController@index')->name('contact');
	Route::post('/contact', 'ContactController@store')->name('contact');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::group(['namespace' => 'Admin'],function(){
	// get admin homepage
	// Route::GET('admin/home', 'adminsController@index');
	// admin profile
	Route::GET('admin/profile', 'ProfileController@index')->name('admin.profile');
	// change profile image
	Route::POST('admin/photo', 'ProfileController@updatePhoto')->name('admin.photo');
	// update admin data
	Route::PUT('admin/update', 'ProfileController@update')->name('admin.update');
	// change admin password
	Route::POST('admin/password', 'ProfileController@password')->name('admin.password');
	// Edit admin education
	Route::GET('admin/education/edit', 'ProfileController@editEducationView')->name('admin.education.edit');
	Route::POST('admin/education/edit', 'ProfileController@editEducation')->name('admin.education.edit');
	// Edit admin experience
	Route::GET('admin/experience/edit', 'ProfileController@editExperienceView')->name('admin.experience.edit');
	Route::POST('admin/experience/edit', 'ProfileController@editExperience')->name('admin.experience.edit');
	// Edit admin personal info
	Route::GET('admin/info/edit', 'ProfileController@editInfoView')->name('admin.info.edit');
	Route::POST('admin/info/edit', 'ProfileController@editInfo')->name('admin.info.edit');
	// get all admins
	Route::resource('admin/admins', 'AdminsController');
	Route::PUT('admin/admins/activate/{admin}', 'AdminsController@activate')->name('admins.activate');

	Route::resource('admin/roles', 'RolesController');
	Route::resource('admin/permissions', 'PermissionsController');
	Route::resource('admin/headlines', 'HeadlinesController');
	Route::resource('admin/topics', 'TopicsController');
	Route::post('admin/topics/{topic}/publish', 'TopicsController@publish')->name('topics.publish');
	Route::resource('admin/events', 'EventsController');
	Route::resource('admin/workshops', 'WorkshopsController');
	
	Route::resource('admin/headsDescription', 'HeadsDescriptionController');
	
	Route::GET('admin/participants19', 'Participants19Controller@index')->name('participants19.index');
	Route::GET('admin/participants19/rejected', 'Participants19Controller@rejected')->name('participants19.rejected');
	Route::POST('admin/participants19/rejected', 'Participants19Controller@rejectedStore')->name('participants19.rejected');
	
	Route::GET('admin/memberssecond19', 'MembersSecondController@index')->name('memberssecond19.index');
	
	Route::GET('admin/opening19', 'Opening19Controller@index')->name('opening19.index');
	Route::GET('admin/opening19/mail', 'Opening19Controller@mail')->name('opening19.mail');
	
	Route::GET('admin/career6', 'Career6Controller@index')->name('career6.index');
	Route::GET('admin/career6/sessions', 'Career6Controller@sessions')->name('career6.session');
	Route::GET('admin/career6/sessions/create', 'Career6Controller@create')->name('career6.session.create');
	Route::POST('admin/career6/sessions/create', 'Career6Controller@store');
	Route::GET('admin/career6/sessions/{session}/edit', 'Career6Controller@edit')->name('career6.session.edit');
	Route::GET('admin/career6/mail', 'Career6Controller@mail')->name('career6.mail');
	Route::PUT('admin/career6/sessions/{session}/update', 'Career6Controller@update')->name('career6.session.update');
	Route::POST('admin/career6/sessions/status/{session}', 'Career6Controller@status')->name('career6.session.status');
	
	// Highway
	Route::GET('admin/highway19', 'Highway19Controller@index')->name('highway19.index');
	Route::GET('admin/highway19/data', 'Highway19Controller@show')->name('highway19.data');
	Route::POST('admin/highway19/data', 'Highway19Controller@data')->name('highway19.data');

	// High Board 20
	Route::GET('admin/highboard20', 'HighBoard20Controller@index')->name('highboard20.index');

	Route::GET('admin/file', 'Career6Controller@file');
	Route::resource('admin/contact', 'ContactController');
});



// Admin routes
Route::group(['namespace' => 'Auth'],function(){
	// get admin login page
	Route::GET('admin','LoginController@showLoginForm')->name('admin.login');
	// login with admin
	Route::POST('admin','LoginController@login');
	// send email for admin to change password
	Route::POST('admin-password/email','ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	// show page of admin to write his email to change password
	Route::GET('admin-password/reset','ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	// reset admin password
	Route::POST('admin-password/reset','ResetPasswordController@reset');
	// get page where admin reset password
	Route::GET('admin-password/reset/{token}','ResetPasswordController@showResetForm')->name('password.reset');
	//logout
	Route::POST('logout','LoginController@logout');
});

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $fillable = [
    	'name', 'email', 'subject', 'message'
    ];
}

app/Http/Controllers/Admin/ContactController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Mail\Career6CompaniesMail;
use App\Models\Contact;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (auth()->user()->can('contact.view')) {
            $contacts = Contact::orderBy('id', 'desc')->paginate(20);
            $unread = Contact::where('seen_by_id', null)->count();
            return view('admin.contacts.index', compact('contacts', 'unread'));
        }
        abort(404);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (auth()->user()->can('contact.create')) {
            $unread = Contact::where('seen_by_id', null)->count();
            return view('admin.contacts.create', compact('unread'));
        }
        abort(404);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (auth()->user()->can('contact.create')) {
            $this->validate($request, [
                'to' => 'required|email',
                'subject' => 'required|string',
                'message' => 'required|string',
            ]);
            Mail::to($request->to)->send(new Career6CompaniesMail($request->subject, $request->message));
            return back()->with(['status' => 'Sent']);
        }
        abort(404);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Contact $contact)
    {
        if (auth()->user()->can('contact.view')) {
            if (!$contact->seen_by_id) {
                $contact->seen_by_id = Auth::id();
                $contact->seen_at = Carbon::now();
                $contact->save();
            }
            $unread = Contact::where('seen_by_id', null)->count();
            return view('admin.contacts.show', compact('contact', 'unread'));
        }
        abort(404);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/ContactController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index()
    {
    	return view('user.contact.index');
    }

    public function store(Request $request)
    {
    	$this->validate($request, [
    		'name' => 'required|string|min:3',
    		'email' => 'required|email|min:3',
    		'subject' => 'required|string|min:3',
    		'message' => 'required|string|min:15',
    	]);
    	$contact = new Contact;
        $request->message = nl2br($request->message);
    	$contact->create($request->all());
    	return back()->with(['status' => 'Sent Successfully!!']);
    }
}

resources/views/admin/contacts/create.blade.php
@extends('admin.layouts.app')

@section('title')
Contacts
@endsection

@section('head')
  <!-- iCheck -->
  <link rel="stylesheet" href="{{ asset('/admin_style/css/froala/froala_editor.css') }}">
  <link rel="stylesheet" href="{{ asset('/admin_style/css/froala/froala_style.css') }}">
  <link rel="stylesheet" href="{{ asset('/admin_style/css/froala/plugins/code_view.css') }}">
  <link rel="stylesheet" href="{{ asset('/admin_style/css/froala/plugins/image_manager.css') }}">
  <link rel="stylesheet" href="{{ asset('/admin_style/css/froala/plugins/image.css') }}">
  <link rel="stylesheet" href="{{ asset('/admin_style/css/froala/plugins/table.css') }}">
  <link rel="stylesheet" href="{{ asset('/admin_style/css/froala/plugins/video.css') }}">
@endsection

@section('content')

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Mailbox
        <small>{{ $unread }} new messages</small>
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-3">
          <a href="compose.html" class="btn btn-primary btn-block margin-bottom">Compose</a>

          <div class="box box-solid">
            <div class="box-header with-border">
              <h3 class="box-title">Folders</h3>

              <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="box-body no-padding">
              <ul class="nav nav-pills nav-stacked">
                <li class="active"><a href="#"><i class="fa fa-inbox"></i> Inbox
                  <span class="label label-primary pull-right">{{ $unread }}</span></a></li>
              </ul>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /. box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Compose New Message</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <form action="{{ route('contact.store') }}" method="POST">
                @csrf
                <div class="form-group">
                  <input class="form-control" autofocus type="email" value="{{ old('to') }}" placeholder="To:" name="to" required>
                </div>
                <div class="form-group">
                  <input class="form-control" value="{{ old('subject') }}" name="subject" required placeholder="Subject:">
                </div>
                <div class="form-group">
                      <textarea id="bodyTextarea" class="form-control" name="message" required style="height: 300px">
                         {{ old('message') }}
                      </textarea>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <div class="pull-right">
                  <button type="submit" class="btn btn-primary"><i class="fa fa-envelope-o"></i> Send</button>
                </div>
              </div>
            </form>
            <!-- /.box-footer -->
          </div>
          <!-- /. box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
@endsection

@section('footer')
<script type="text/javascript" src="{{ asset('/admin_style/js/froala/froala_editor.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/align.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/code_beautifier.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/code_view.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/draggable.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/image.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/image_manager.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/link.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/lists.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/paragraph_format.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/paragraph_style.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/table.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/video.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/url.min.js') }}"></script>
  <script type="text/javascript" src="{{ asset('/admin_style/js/froala/plugins/entities.min.js') }}"></script>

  <script>
      $(function(){
        $('#bodyTextarea')
          .froalaEditor({enter: $.FroalaEditor.ENTER_BR, placeholderText: "Write the email..."})
      });
  </script>
@endsection

resources/views/admin/contacts/index.blade.php
@extends('admin.layouts.app')

@section('title')
Contacts
@endsection

@section('head')
	<!-- iCheck -->
  <link rel="stylesheet" href="{{ asset('/admin_style/css/flat/blue.css') }}">
@endsection

@section('content')

<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Mailbox
        <small>{{ $unread }} new messages</small>
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-3">
          <a href="compose.html" class="btn btn-primary btn-block margin-bottom">Compose</a>

          <div class="box box-solid">
            <div class="box-header with-border">
              <h3 class="box-title">Folders</h3>

              <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="box-body no-padding">
              <ul class="nav nav-pills nav-stacked">
                <li class="active"><a href="#"><i class="fa fa-inbox"></i> Inbox
                  <span class="label label-primary pull-right">{{ $unread }}</span></a></li>
              </ul>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /. box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Inbox</h3>
              <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
              <div class="mailbox-controls">
                <!-- Check all button -->
                <button type="button" class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i>
                </button>
                <div class="btn-group">
                  <button type="button" class="btn btn-default btn-sm"><i class="fa fa-trash-o"></i></button>
                </div>
                <!-- /.btn-group -->
                </div>
                <!-- /.pull-right -->
              </div>
              <div class="table-responsive mailbox-messages">
                <table class="table table-hover table-striped">
                  <tbody>
                    @foreach ($contacts as $contact)
	                  <tr>
                    	<td><input type="checkbox"></td>
	                    <td class="mailbox-name"><a href="{{ route('contact.show', $contact->id) }}">{{ $contact->name }}</a></td>
	                    <td class="mailbox-subject">
	                    	@if ($contact->seen_by_id)
	                    		{{ $contact->subject }}
	                    	@else
	                    		<b>{{ $contact->subject }}</b>
	                    	@endif
	                    </td>
	                    <td class="mailbox-date">{{ $contact->created_at->diffForHumans() }}</td>
                  		</tr>
                    @endforeach
                  </tbody>
                </table>
                <!-- /.table -->
              </div>
              <!-- /.mail-box-messages -->
            </div>
            <!-- /.box-body -->
            <div class="box-footer no-padding">
              <div class="mailbox-controls">
                <!-- Check all button -->
                <button type="button" class="btn btn-default btn-sm checkbox-toggle"><i class="fa fa-square-o"></i>
                </button>
                <div class="btn-group">
                  <button type="button" class="btn btn-default btn-sm"><i class="fa fa-trash-o"></i></button>
                </div>
                <!-- /.btn-group -->
                  <!-- /.btn-group -->
                <div class="pull-right">
                	{{ $contacts->links() }}
                </div>
                </div>
                <!-- /.pull-right -->
              </div>
            </div>
          </div>
          <!-- /. box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
@endsection

@section('footer')
<!-- iCheck -->
<script src="{{ asset('/admin_style/js/icheck.min.js') }}"></script>
<!-- Page Script -->
<script>
  $(function () {
    //Enable iCheck plugin for checkboxes
    //iCheck for checkbox and radio inputs
    $('.mailbox-messages input[type="checkbox"]').iCheck({
      checkboxClass: 'icheckbox_flat-blue',
      radioClass: 'iradio_flat-blue'
    });

    //Enable check and uncheck all functionality
    $(".checkbox-toggle").click(function () {
      var clicks = $(this).data('clicks');
      if (clicks) {
        //Uncheck all checkboxes
        $(".mailbox-messages input[type='checkbox']").iCheck("uncheck");
        $(".fa", this).removeClass("fa-check-square-o").addClass('fa-square-o');
      } else {
        //Check all checkboxes
        $(".mailbox-messages input[type='checkbox']").iCheck("check");
        $(".fa", this).removeClass("fa-square-o").addClass('fa-check-square-o');
      }
      $(this).data("clicks", !clicks);
    });
  });
</script>
@endsection

resources/views/admin/contacts/show.blade.php
@extends('admin.layouts.app')

@section('title')
Contacts
@endsection

@section('head')

@endsection

@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Read Contact
      </h1>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-3">
          <a href="compose.html" class="btn btn-primary btn-block margin-bottom">Compose</a>

          <div class="box box-solid">
            <div class="box-header with-border">
              <h3 class="box-title">Folders</h3>

              <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="box-body no-padding">
              <ul class="nav nav-pills nav-stacked">
                <li><a href="mailbox.html"><i class="fa fa-inbox"></i> Inbox
                  <span class="label label-primary pull-right">{{ $unread }}</span></a></li>
              </ul>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /. box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Read Contact</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
              <div class="mailbox-read-info">
                <h3>{{ $contact->subject }}</h3>
                <h5>From: {{ $contact->email }}
                  <span class="mailbox-read-time pull-right">{{ $contact->created_at->isoFormat('LLL') }}</span></h5>
              </div>
              <!-- /.mailbox-read-info -->
              <div class="mailbox-controls with-border text-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Delete">
                    <i class="fa fa-trash-o"></i></button>
                  <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Reply">
                    <i class="fa fa-reply"></i></button>
                </div>
                <!-- /.btn-group -->
              </div>
              <!-- /.mailbox-controls -->
              <div class="mailbox-read-message">
                {!! $contact->message !!}
              </div>
              <!-- /.mailbox-read-message -->
            </div>
            <!-- /.box-footer -->
            <div class="box-footer">
              <div class="pull-right">
                <button type="button" class="btn btn-default"><i class="fa fa-reply"></i> Reply</button>
              </div>
              <button type="button" class="btn btn-default"><i class="fa fa-trash-o"></i> Delete</button>
            </div>
            <!-- /.box-footer -->
          </div>
          <!-- /. box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
@endsection

@section('footer')

@endsection